### PR TITLE
Create gal_bico.json

### PR DESCRIPTION
**Pull request by Bicogal**

### CODE REVIEW

**Comment by szabgab** [comment]
It would be nice if you could fix the error in this PR.

**Comment by Bicogal** [comment]
Error is fixed

**Comment by szabgab** [comment]
Your github username is `Bicogal` so the file should be called `bicogal.json` and the `github` field inside should have `bicogal`

**Comment by szabgab** [comment]
lower case ... `bicogal`

**Comment by szabgab** [comment]
Now it looks good. Actually it seems that the last failure was due to some issue in GitHub, not with your file or our code.

**Comment by szabgab** [comment]
Maybe also add a picture of yourself or an avatar to your github account so it will show up on our site.

**Pull request merged**
